services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5016:5016" # Mapeia a porta 5016 do host para a porta 5016 do container
    networks:
      - app-network

  frontend:
    build:
      context: ./cep-spa
      dockerfile: Dockerfile
    ports:
      - "5015:5015" # Mapeia a porta 5015 do host para a porta 5015 do container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
